// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: oac/v1/harness.proto

package oacv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RunSessionRequest is the harness → orchestrator envelope.
// Exactly one frame field is set per message.
type RunSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*RunSessionRequest_Heartbeat
	//	*RunSessionRequest_Idle
	//	*RunSessionRequest_Complete
	//	*RunSessionRequest_SgpEvent
	Frame         isRunSessionRequest_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunSessionRequest) Reset() {
	*x = RunSessionRequest{}
	mi := &file_oac_v1_harness_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunSessionRequest) ProtoMessage() {}

func (x *RunSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oac_v1_harness_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunSessionRequest.ProtoReflect.Descriptor instead.
func (*RunSessionRequest) Descriptor() ([]byte, []int) {
	return file_oac_v1_harness_proto_rawDescGZIP(), []int{0}
}

func (x *RunSessionRequest) GetFrame() isRunSessionRequest_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *RunSessionRequest) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Frame.(*RunSessionRequest_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *RunSessionRequest) GetIdle() *Idle {
	if x != nil {
		if x, ok := x.Frame.(*RunSessionRequest_Idle); ok {
			return x.Idle
		}
	}
	return nil
}

func (x *RunSessionRequest) GetComplete() *Complete {
	if x != nil {
		if x, ok := x.Frame.(*RunSessionRequest_Complete); ok {
			return x.Complete
		}
	}
	return nil
}

func (x *RunSessionRequest) GetSgpEvent() *SGPEvent {
	if x != nil {
		if x, ok := x.Frame.(*RunSessionRequest_SgpEvent); ok {
			return x.SgpEvent
		}
	}
	return nil
}

type isRunSessionRequest_Frame interface {
	isRunSessionRequest_Frame()
}

type RunSessionRequest_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,1,opt,name=heartbeat,proto3,oneof"`
}

type RunSessionRequest_Idle struct {
	Idle *Idle `protobuf:"bytes,2,opt,name=idle,proto3,oneof"`
}

type RunSessionRequest_Complete struct {
	Complete *Complete `protobuf:"bytes,3,opt,name=complete,proto3,oneof"`
}

type RunSessionRequest_SgpEvent struct {
	SgpEvent *SGPEvent `protobuf:"bytes,4,opt,name=sgp_event,json=sgpEvent,proto3,oneof"`
}

func (*RunSessionRequest_Heartbeat) isRunSessionRequest_Frame() {}

func (*RunSessionRequest_Idle) isRunSessionRequest_Frame() {}

func (*RunSessionRequest_Complete) isRunSessionRequest_Frame() {}

func (*RunSessionRequest_SgpEvent) isRunSessionRequest_Frame() {}

// SGPEvent carries a JSON-serialized sgp.Event emitted by the harness.
// The orchestrator deserializes and appends it to the session graph store.
type SGPEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SGPEvent) Reset() {
	*x = SGPEvent{}
	mi := &file_oac_v1_harness_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SGPEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SGPEvent) ProtoMessage() {}

func (x *SGPEvent) ProtoReflect() protoreflect.Message {
	mi := &file_oac_v1_harness_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SGPEvent.ProtoReflect.Descriptor instead.
func (*SGPEvent) Descriptor() ([]byte, []int) {
	return file_oac_v1_harness_proto_rawDescGZIP(), []int{1}
}

func (x *SGPEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// RunSessionResponse is the orchestrator → harness envelope.
// Exactly one frame field is set per message.
type RunSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Frame:
	//
	//	*RunSessionResponse_SessionContext
	//	*RunSessionResponse_Event
	//	*RunSessionResponse_SuspendWarning
	Frame         isRunSessionResponse_Frame `protobuf_oneof:"frame"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunSessionResponse) Reset() {
	*x = RunSessionResponse{}
	mi := &file_oac_v1_harness_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunSessionResponse) ProtoMessage() {}

func (x *RunSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oac_v1_harness_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunSessionResponse.ProtoReflect.Descriptor instead.
func (*RunSessionResponse) Descriptor() ([]byte, []int) {
	return file_oac_v1_harness_proto_rawDescGZIP(), []int{2}
}

func (x *RunSessionResponse) GetFrame() isRunSessionResponse_Frame {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *RunSessionResponse) GetSessionContext() *SessionContext {
	if x != nil {
		if x, ok := x.Frame.(*RunSessionResponse_SessionContext); ok {
			return x.SessionContext
		}
	}
	return nil
}

func (x *RunSessionResponse) GetEvent() *Event {
	if x != nil {
		if x, ok := x.Frame.(*RunSessionResponse_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *RunSessionResponse) GetSuspendWarning() *SuspendWarning {
	if x != nil {
		if x, ok := x.Frame.(*RunSessionResponse_SuspendWarning); ok {
			return x.SuspendWarning
		}
	}
	return nil
}

type isRunSessionResponse_Frame interface {
	isRunSessionResponse_Frame()
}

type RunSessionResponse_SessionContext struct {
	SessionContext *SessionContext `protobuf:"bytes,1,opt,name=session_context,json=sessionContext,proto3,oneof"`
}

type RunSessionResponse_Event struct {
	Event *Event `protobuf:"bytes,2,opt,name=event,proto3,oneof"`
}

type RunSessionResponse_SuspendWarning struct {
	SuspendWarning *SuspendWarning `protobuf:"bytes,3,opt,name=suspend_warning,json=suspendWarning,proto3,oneof"`
}

func (*RunSessionResponse_SessionContext) isRunSessionResponse_Frame() {}

func (*RunSessionResponse_Event) isRunSessionResponse_Frame() {}

func (*RunSessionResponse_SuspendWarning) isRunSessionResponse_Frame() {}

// Heartbeat is sent periodically by the harness to keep the session alive.
// The orchestrator resets the dormancy inactivity timer on receipt.
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_oac_v1_harness_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_oac_v1_harness_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_oac_v1_harness_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Idle signals that the harness has no pending work and consents to suspension.
// Receipt triggers an ACTIVE → DORMANT lifecycle transition.
type Idle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Idle) Reset() {
	*x = Idle{}
	mi := &file_oac_v1_harness_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Idle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Idle) ProtoMessage() {}

func (x *Idle) ProtoReflect() protoreflect.Message {
	mi := &file_oac_v1_harness_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Idle.ProtoReflect.Descriptor instead.
func (*Idle) Descriptor() ([]byte, []int) {
	return file_oac_v1_harness_proto_rawDescGZIP(), []int{4}
}

// Complete signals that the harness has finished all work for this session.
// Receipt triggers an ACTIVE → COMPLETE lifecycle transition. Terminal.
type Complete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Complete) Reset() {
	*x = Complete{}
	mi := &file_oac_v1_harness_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Complete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Complete) ProtoMessage() {}

func (x *Complete) ProtoReflect() protoreflect.Message {
	mi := &file_oac_v1_harness_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Complete.ProtoReflect.Descriptor instead.
func (*Complete) Descriptor() ([]byte, []int) {
	return file_oac_v1_harness_proto_rawDescGZIP(), []int{5}
}

// SessionContext is sent by the orchestrator once on stream open.
// Contains the canonical SGP message array assembled by the Session Graph Store.
type SessionContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// history_json is a JSON-serialized []sgp.Message (root→head linear path).
	// Empty for brand-new sessions.
	HistoryJson []byte `protobuf:"bytes,1,opt,name=history_json,json=historyJson,proto3" json:"history_json,omitempty"`
	// needs_response is true when the head node is a user or tool message,
	// indicating that the agent has not yet produced a reply.
	NeedsResponse bool `protobuf:"varint,2,opt,name=needs_response,json=needsResponse,proto3" json:"needs_response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionContext) Reset() {
	*x = SessionContext{}
	mi := &file_oac_v1_harness_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionContext) ProtoMessage() {}

func (x *SessionContext) ProtoReflect() protoreflect.Message {
	mi := &file_oac_v1_harness_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionContext.ProtoReflect.Descriptor instead.
func (*SessionContext) Descriptor() ([]byte, []int) {
	return file_oac_v1_harness_proto_rawDescGZIP(), []int{6}
}

func (x *SessionContext) GetHistoryJson() []byte {
	if x != nil {
		return x.HistoryJson
	}
	return nil
}

func (x *SessionContext) GetNeedsResponse() bool {
	if x != nil {
		return x.NeedsResponse
	}
	return false
}

// Event carries a single inbound event for delivery to the harness.
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	ChannelName   string                 `protobuf:"bytes,2,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_oac_v1_harness_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_oac_v1_harness_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_oac_v1_harness_proto_rawDescGZIP(), []int{7}
}

func (x *Event) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Event) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// SuspendWarning is an optional pre-dormancy notice sent before an
// orchestrator-side inactivity timeout fires.
type SuspendWarning struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuspensionAt  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=suspension_at,json=suspensionAt,proto3" json:"suspension_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendWarning) Reset() {
	*x = SuspendWarning{}
	mi := &file_oac_v1_harness_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendWarning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendWarning) ProtoMessage() {}

func (x *SuspendWarning) ProtoReflect() protoreflect.Message {
	mi := &file_oac_v1_harness_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendWarning.ProtoReflect.Descriptor instead.
func (*SuspendWarning) Descriptor() ([]byte, []int) {
	return file_oac_v1_harness_proto_rawDescGZIP(), []int{8}
}

func (x *SuspendWarning) GetSuspensionAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SuspensionAt
	}
	return nil
}

var File_oac_v1_harness_proto protoreflect.FileDescriptor

const file_oac_v1_harness_proto_rawDesc = "" +
	"\n" +
	"\x14oac/v1/harness.proto\x12\x06oac.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd4\x01\n" +
	"\x11RunSessionRequest\x121\n" +
	"\theartbeat\x18\x01 \x01(\v2\x11.oac.v1.HeartbeatH\x00R\theartbeat\x12\"\n" +
	"\x04idle\x18\x02 \x01(\v2\f.oac.v1.IdleH\x00R\x04idle\x12.\n" +
	"\bcomplete\x18\x03 \x01(\v2\x10.oac.v1.CompleteH\x00R\bcomplete\x12/\n" +
	"\tsgp_event\x18\x04 \x01(\v2\x10.oac.v1.SGPEventH\x00R\bsgpEventB\a\n" +
	"\x05frame\"$\n" +
	"\bSGPEvent\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"\xca\x01\n" +
	"\x12RunSessionResponse\x12A\n" +
	"\x0fsession_context\x18\x01 \x01(\v2\x16.oac.v1.SessionContextH\x00R\x0esessionContext\x12%\n" +
	"\x05event\x18\x02 \x01(\v2\r.oac.v1.EventH\x00R\x05event\x12A\n" +
	"\x0fsuspend_warning\x18\x03 \x01(\v2\x16.oac.v1.SuspendWarningH\x00R\x0esuspendWarningB\a\n" +
	"\x05frame\"E\n" +
	"\tHeartbeat\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x06\n" +
	"\x04Idle\"\n" +
	"\n" +
	"\bComplete\"Z\n" +
	"\x0eSessionContext\x12!\n" +
	"\fhistory_json\x18\x01 \x01(\fR\vhistoryJson\x12%\n" +
	"\x0eneeds_response\x18\x02 \x01(\bR\rneedsResponse\"_\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12!\n" +
	"\fchannel_name\x18\x02 \x01(\tR\vchannelName\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"Q\n" +
	"\x0eSuspendWarning\x12?\n" +
	"\rsuspension_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\fsuspensionAt2Y\n" +
	"\x0eHarnessService\x12G\n" +
	"\n" +
	"RunSession\x12\x19.oac.v1.RunSessionRequest\x1a\x1a.oac.v1.RunSessionResponse(\x010\x01BAZ?github.com/restrukt-ai/openagentcontainers/pkg/api/oac/v1;oacv1b\x06proto3"

var (
	file_oac_v1_harness_proto_rawDescOnce sync.Once
	file_oac_v1_harness_proto_rawDescData []byte
)

func file_oac_v1_harness_proto_rawDescGZIP() []byte {
	file_oac_v1_harness_proto_rawDescOnce.Do(func() {
		file_oac_v1_harness_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oac_v1_harness_proto_rawDesc), len(file_oac_v1_harness_proto_rawDesc)))
	})
	return file_oac_v1_harness_proto_rawDescData
}

var file_oac_v1_harness_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_oac_v1_harness_proto_goTypes = []any{
	(*RunSessionRequest)(nil),     // 0: oac.v1.RunSessionRequest
	(*SGPEvent)(nil),              // 1: oac.v1.SGPEvent
	(*RunSessionResponse)(nil),    // 2: oac.v1.RunSessionResponse
	(*Heartbeat)(nil),             // 3: oac.v1.Heartbeat
	(*Idle)(nil),                  // 4: oac.v1.Idle
	(*Complete)(nil),              // 5: oac.v1.Complete
	(*SessionContext)(nil),        // 6: oac.v1.SessionContext
	(*Event)(nil),                 // 7: oac.v1.Event
	(*SuspendWarning)(nil),        // 8: oac.v1.SuspendWarning
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_oac_v1_harness_proto_depIdxs = []int32{
	3,  // 0: oac.v1.RunSessionRequest.heartbeat:type_name -> oac.v1.Heartbeat
	4,  // 1: oac.v1.RunSessionRequest.idle:type_name -> oac.v1.Idle
	5,  // 2: oac.v1.RunSessionRequest.complete:type_name -> oac.v1.Complete
	1,  // 3: oac.v1.RunSessionRequest.sgp_event:type_name -> oac.v1.SGPEvent
	6,  // 4: oac.v1.RunSessionResponse.session_context:type_name -> oac.v1.SessionContext
	7,  // 5: oac.v1.RunSessionResponse.event:type_name -> oac.v1.Event
	8,  // 6: oac.v1.RunSessionResponse.suspend_warning:type_name -> oac.v1.SuspendWarning
	9,  // 7: oac.v1.Heartbeat.timestamp:type_name -> google.protobuf.Timestamp
	9,  // 8: oac.v1.SuspendWarning.suspension_at:type_name -> google.protobuf.Timestamp
	0,  // 9: oac.v1.HarnessService.RunSession:input_type -> oac.v1.RunSessionRequest
	2,  // 10: oac.v1.HarnessService.RunSession:output_type -> oac.v1.RunSessionResponse
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_oac_v1_harness_proto_init() }
func file_oac_v1_harness_proto_init() {
	if File_oac_v1_harness_proto != nil {
		return
	}
	file_oac_v1_harness_proto_msgTypes[0].OneofWrappers = []any{
		(*RunSessionRequest_Heartbeat)(nil),
		(*RunSessionRequest_Idle)(nil),
		(*RunSessionRequest_Complete)(nil),
		(*RunSessionRequest_SgpEvent)(nil),
	}
	file_oac_v1_harness_proto_msgTypes[2].OneofWrappers = []any{
		(*RunSessionResponse_SessionContext)(nil),
		(*RunSessionResponse_Event)(nil),
		(*RunSessionResponse_SuspendWarning)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oac_v1_harness_proto_rawDesc), len(file_oac_v1_harness_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oac_v1_harness_proto_goTypes,
		DependencyIndexes: file_oac_v1_harness_proto_depIdxs,
		MessageInfos:      file_oac_v1_harness_proto_msgTypes,
	}.Build()
	File_oac_v1_harness_proto = out.File
	file_oac_v1_harness_proto_goTypes = nil
	file_oac_v1_harness_proto_depIdxs = nil
}
