// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: oac/v1/harness.proto

package oacv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/restrukt-ai/openagentcontainers/pkg/api/oac/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// HarnessServiceName is the fully-qualified name of the HarnessService service.
	HarnessServiceName = "oac.v1.HarnessService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// HarnessServiceRunSessionProcedure is the fully-qualified name of the HarnessService's RunSession
	// RPC.
	HarnessServiceRunSessionProcedure = "/oac.v1.HarnessService/RunSession"
)

// HarnessServiceClient is a client for the oac.v1.HarnessService service.
type HarnessServiceClient interface {
	RunSession(context.Context) *connect.BidiStreamForClient[v1.RunSessionRequest, v1.RunSessionResponse]
}

// NewHarnessServiceClient constructs a client for the oac.v1.HarnessService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewHarnessServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) HarnessServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	harnessServiceMethods := v1.File_oac_v1_harness_proto.Services().ByName("HarnessService").Methods()
	return &harnessServiceClient{
		runSession: connect.NewClient[v1.RunSessionRequest, v1.RunSessionResponse](
			httpClient,
			baseURL+HarnessServiceRunSessionProcedure,
			connect.WithSchema(harnessServiceMethods.ByName("RunSession")),
			connect.WithClientOptions(opts...),
		),
	}
}

// harnessServiceClient implements HarnessServiceClient.
type harnessServiceClient struct {
	runSession *connect.Client[v1.RunSessionRequest, v1.RunSessionResponse]
}

// RunSession calls oac.v1.HarnessService.RunSession.
func (c *harnessServiceClient) RunSession(ctx context.Context) *connect.BidiStreamForClient[v1.RunSessionRequest, v1.RunSessionResponse] {
	return c.runSession.CallBidiStream(ctx)
}

// HarnessServiceHandler is an implementation of the oac.v1.HarnessService service.
type HarnessServiceHandler interface {
	RunSession(context.Context, *connect.BidiStream[v1.RunSessionRequest, v1.RunSessionResponse]) error
}

// NewHarnessServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewHarnessServiceHandler(svc HarnessServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	harnessServiceMethods := v1.File_oac_v1_harness_proto.Services().ByName("HarnessService").Methods()
	harnessServiceRunSessionHandler := connect.NewBidiStreamHandler(
		HarnessServiceRunSessionProcedure,
		svc.RunSession,
		connect.WithSchema(harnessServiceMethods.ByName("RunSession")),
		connect.WithHandlerOptions(opts...),
	)
	return "/oac.v1.HarnessService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case HarnessServiceRunSessionProcedure:
			harnessServiceRunSessionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedHarnessServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedHarnessServiceHandler struct{}

func (UnimplementedHarnessServiceHandler) RunSession(context.Context, *connect.BidiStream[v1.RunSessionRequest, v1.RunSessionResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("oac.v1.HarnessService.RunSession is not implemented"))
}
